"""add companion messages

Revision ID: 2c460e9b89a7
Revises: d03d1aa9dbe0
Create Date: 2026-07-20 15:06:13.573861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c460e9b89a7'
down_revision = 'd03d1aa9dbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_companion_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companion_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companion_message')
    # ### end Alembic commands ###
